# Generated by Django 6.0.6 on 2026-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('phone', models.IntegerField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
