# Generated by Django 6.0.6 on 2026-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
