# Generated by Django 6.0.6 on 2026-06-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0003_tb_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tb_comments',
            name='user',
        ),
    ]
