# Generated by Django 6.0.6 on 2026-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0004_remove_tb_comments_post_remove_tb_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
