# Generated by Django 6.0.6 on 2026-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0005_tb_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_post',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
