# Generated by Django 6.0.6 on 2026-06-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0006_alter_tb_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogg_app.tb_post'),
        ),
    ]
