# Generated by Django 6.0.6 on 2026-06-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0007_tb_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogg_app.tb_user'),
        ),
        migrations.AddField(
            model_name='tb_post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogg_app.tb_user'),
        ),
    ]
