# Generated by Django 6.0.6 on 2026-06-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0008_tb_comments_user_tb_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogg_app.tb_post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogg_app.tb_user')),
            ],
        ),
    ]
