# Generated by Django 6.0.6 on 2026-06-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0009_tb_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_user',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
