# Generated by Django 6.0.6 on 2026-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg_app', '0010_alter_tb_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
